const CREATE_POST_REQUESTS = 'CREATE_POST_REQUESTS'
const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'
const CREATE_POST_FAILURE = 'CREATE_POST_FAILURE'

const DELETE_POST_REQUESTS = 'DELETE_POST_REQUESTS'
const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'
const DELETE_POST_FAILURE = 'DELETE_POST_FAILURE'

const FETCH_POSTS_REQUESTS = 'FETCH_POSTS_REQUESTS'
const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS'
const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE'
const SHOW_MORE = 'SHOW_MORE'

const SET_SHOWCASE = 'SET_SHOWCASE'
const CLOSE_SHOWCASE = 'CLOSE_SHOWCASE'


export {
    CREATE_POST_REQUESTS,
    CREATE_POST_SUCCESS,
    CREATE_POST_FAILURE,

    DELETE_POST_REQUESTS,
    DELETE_POST_SUCCESS,
    DELETE_POST_FAILURE,

    FETCH_POSTS_REQUESTS,
    FETCH_POSTS_SUCCESS,
    FETCH_POSTS_FAILURE,
    SHOW_MORE,

    SET_SHOWCASE,
    CLOSE_SHOWCASE
}
